server:
  servlet:
    context-path: /api
spring:
  application:
     name: app
  profiles:
     active: dev
  rabbitmq:
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    port: ${SPRING_RABBITMQ_PORT:5672}
    host: ${SPRING_RABBITMQ_HOST:localhost}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      timeout: ${SPRING_DATA_REDIS_TIMEOUT:6379}
      sentinel:
        username:
  jpa:
    open-in-view: false
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path:  /swagger-ui.html

logging:
  level:
    feign: DEBUG


vehicle:
 queue:
  name: vehicle_creation_queue
 exchange:
  name: vehicle_exchange
 routing:
  key: vehicle_routing_key

dead:
   letter:
     queue:
       name: vehicle_creation_dlq
     exchange:
       name: vehicle_creation_dlx_exchange
     routing:
       key: vehicle_dlq_routing_key

retry:
  queue:
    name: vehicle_creation_retry_queue