

server:
  servlet:
    context-path: /api
spring:
  application:
     name: app
  profiles:
     active: dev

  jpa:
    open-in-view: false
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path:  /swagger-ui.html