server:
  servlet:
    context-path: /api
spring:
  application:
    name: app
  profiles:
    active: test
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: true
logging:
  level:
    feign: DEBUG

vehicle:
  queue:
    name: vehicle_creation_queue
  exchange:
    name: vehicle_exchange
  routing:
    key: vehicle_routing_key

dead:
  letter:
    queue:
      name: vehicle_creation_dlq
    exchange:
      name: vehicle_creation_dlx_exchange
    routing:
      key: vehicle_dlq_routing_key

retry:
  queue:
    name: vehicle_creation_retry_queue
