

server:
  servlet:
    context-path: /api
spring:
  application:
     name: app
  profiles:
     active: dev
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: localhost
  jpa:
    open-in-view: false
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path:  /swagger-ui.html

logging:
  level:
    feign: DEBUG


vehicle:
 queue:
  name: vehicle_creation_queue
 exchange:
  name: vehicle_exchange
 routing:
  key: vehicle_routing_key

dead:
   letter:
     queue:
       name: vehicle_creation_dlq
     exchange:
       name: vehicle_creation_dlx_exchange
     routing:
       key: vehicle_dlq_routing_key

retry:
  queue:
    name: vehicle_creation_retry_queue